### ISSUE TITLE
Calendar - HTML - Control-Zoom Issue

### ISSUE THREAD

**Issue by Ereasai** [cse110-fa22-group16/cse110-fa22-group16#15]
### Location
**calendar-html**, index.html, calendar-style.css

### Description
control + plus messes up the text. The size of the boxes gets messed up.

### Suggestion
n/a

**Comment by ZiyuWang0113** [comment]
Invalid feature, relative position will mess up the zoom-in fitting. Will be fixed later after this quarter if possible
