### ISSUE TITLE
Hello- DOCS - Create ADR

### ISSUE THREAD

**Issue by shantellemeganserafin** [cse110-fa22-group16/cse110-fa22-group16#37]
Location
hello

Description
adr for all hello pages decisions

Suggestion

**Comment by shantellemeganserafin** [comment]
Location
hello

Description
adr for all hello pages decisions

Suggestion

**Comment by tianyuchen01** [comment]
done Nov 10 (migrating ADR-20221103 contents about hello pages' ADR)
