### ISSUE TITLE
General - New Variable to select correct month

### ISSUE THREAD

**Issue by ZiyuWang0113** [cse110-fa22-group16/cse110-fa22-group16#91]
**hello**: Setup a `currentState` in the localStorage, set to `null` when ~~we `do the entry`~~ or click `my calendar`. 
              ~~When we click *let's go*, `currentState` is `null` in localStorage before entering any other pages~~

**edit**: When editing XX date's entry, set `currentState` to XX, if XX is today, set to today as well

**calendar**: If `currentState` is `null`, display the current month, if not `null`, display the month of `currentState`

ADR updated in the branch calendar

**Comment by shantellemeganserafin** [comment]
Complete for team hello

**Comment by Ereasai** [comment]
Complete for edit and calendar.
